### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by panpan0000** [mikesart/inotify-info#17] opened 2023-08-29 05:03 UTC
gdb shows
```
Reading symbols from ./_release/inotify-info...
(gdb) run
Starting program: /tmp/inotify-info/_release/inotify-info
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
------------------------------------------------------------------------------
INotify Limits:
  max_queued_events    16384
  max_user_instances   524288
  max_user_watches     524288
------------------------------------------------------------------------------

Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=buf@entry=0x7fffffffde10 "Uid:\t0\t0\t0\t0\n", n=n@entry=256, fp=fp@entry=0x0) at ./libio/iofgets.c:47
47	./libio/iofgets.c: No such file or directory.

```

enviroments:

- gcc version 11.4.0
- DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
-

**Comment by suside** [comment] 2023-08-30 07:16
This is duplicate of [!15](https://github.com/mikesart/inotify-info/issues/15) but im not sure if this project is maintained anymore though

**Comment by mikesart** [comment] 2023-09-05 02:39
Duplicate of #15. Made a commit which maybe/hopefully will fix this but we can track it over there. Thanks.

**Closed by mikesart** 2023-09-05 02:39 UTC
